### ISSUE TITLE
Обработка подтверждения заказа

### ISSUE THREAD

**Issue by k-sannikov** [Klaypexx/traveline_practice#10]
Не знаю, обсуждали ли вы на лекции обработку некорректного ввода, но хотелось бы тут видеть ```else``` c сообщением, что заказ отменен, т.к. не получено подтверждение, Пустую строку не считать за подтверждение, а также прочитать про методы Trim и ToLower, они тебе помогут сократить условие и подкорректировать не очень корректный ввод пользователя, например, с лишними проблемами
А еще хотелось бы перед запросом подтверждения увидеть сообщение о том, что именно нужно ввести в консоль для подтверждения и остановиться на каком-то одном варианте, например, "Да"
https://github.com/Klaypexx/traveline_practice/blob/ca172bf5d829598ad8149e106e36039a38c38b17/lecture1(14.03)/test/test/Program.cs#L25

**Comment by Klaypexx** [comment]
Если я использую ToLower, то получается я не смогу нормально проверить "Да". Либо его можно как то восстановить?
