### ISSUE TITLE
Убрать дублирование кода

### ISSUE THREAD

**Issue by k-sannikov** [Klaypexx/traveline_practice#24]
У тебя есть 2 типа операций, которые требуют НЕ пустой словарь и операции которым все равно на то пустой он или нет, из-за этого у тебя очень много повторяющегося кода, таких ситуаций надо избегать. Я думаю существует много вариаций как это можно сделать более элегантно и правильно, подумай пока сам над этим, если будут сложности, то пиши мне
https://github.com/Klaypexx/traveline_practice/blob/ca172bf5d829598ad8149e106e36039a38c38b17/homework1/dictionary/Program.cs#L208

**Comment by Klaypexx** [comment]
Сделал сверху над switch отдельно проверку. Если будет нужно, то вынесу ее в отдельную функцию.
