### ISSUE TITLE
Корректно обработать исключение

### ISSUE THREAD

**Issue by k-sannikov** [Klaypexx/traveline_practice#26]
тут ты просто ловишь  и перевыбрасываешь исключение никак его не обрабатывая, таким образом при возникновении исключения у тебя программа экстренно завершится и в консоли будет непонятный вывод для пользователя
https://github.com/Klaypexx/traveline_practice/blob/ca172bf5d829598ad8149e106e36039a38c38b17/homework1/dictionary/Program.cs#L45

**Comment by k-sannikov** [comment]
самый лучший способ обработки - это выдать сообщение пользователю и попробовать повторить операцию

**Comment by Klaypexx** [comment]
Обработал исключения. Также вместо обычной команды StreamReader reader = new StreamReader(refs) начал использовать using (StreamReader reader = new StreamReader(refs)). Как я понял, она нужна для автоматического освобождение ресурсов после завершения использования объекта.
